CXX=c++
CXXFLAGS=-std=c++11 -I . -Wall -Werror -fPIC -O2 \
-Wsign-compare -Wpointer-arith -Wswitch-default -Wswitch-enum -Wshadow

all: Blowfish.o BlowfishCfb64.o

clean:
	rm -f Blowfish.o BlowfishCfb64.o

Makefile: ;

.PHONY: all clean

